/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projectpbo;

import java.io.InputStream;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Ella
 */
public class databarang extends javax.swing.JFrame {

    /**
     * Creates new form databarang
     */
    public databarang() {
        initComponents();
        tampil_data();
    }
    
    public void tampil_data() {
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("Kode Barang");
        model.addColumn("Nama Barang");
        model.addColumn("Bahan");
        model.addColumn("Stok");
        model.addColumn("Harga");
        try {
            String sql = "SELECT * FROM barang";
            java.sql.Connection conn = (Connection)Konfig.configDB();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet res = stm.executeQuery(sql);
            
            while(res.next()) {
                model.addRow(new Object[]{
                    res.getString(1),
                    res.getString(2),
                    res.getString(3),
                    res.getString(4),
                    res.getString(5)});
            }
            tabelbarang.setModel(model);
        } catch (SQLException e) {
            System.out.println("Error :"+ e.getMessage());
        }
    }
    
    public void tampil() {
        DefaultTableModel model = new DefaultTableModel();
         model.addColumn("Kode Barang");
        model.addColumn("Nama Barang");
        model.addColumn("Bahan");
        model.addColumn("Stok");
        model.addColumn("Harga");
        try {
            String sql = "SELECT * FROM barang where kode_barang ='"+cari.getText()+"'";
            java.sql.Connection conn = (Connection)Konfig.configDB();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet res = stm.executeQuery(sql);
            
            while(res.next()) {
                model.addRow(new Object[]{
                    res.getString(1),
                    res.getString(2),
                    res.getString(3),
                    res.getString(4),
                    res.getString(5)});
            }
            tabelbarang.setModel(model);
        } catch (SQLException e) {
            System.out.println("Error :"+ e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtharga = new javax.swing.JTextField();
        next = new javax.swing.JLabel();
        back = new javax.swing.JLabel();
        exit = new javax.swing.JLabel();
        cari = new javax.swing.JTextField();
        txtstok = new javax.swing.JTextField();
        txtbahan = new javax.swing.JTextField();
        txtnama_barang = new javax.swing.JTextField();
        txtkode_barang = new javax.swing.JTextField();
        btncari = new javax.swing.JButton();
        batal = new javax.swing.JButton();
        hapus = new javax.swing.JButton();
        edit = new javax.swing.JButton();
        simpan = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelbarang = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(400, 200));
        setMaximumSize(new java.awt.Dimension(1229, 700));
        setMinimumSize(new java.awt.Dimension(1229, 700));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtharga.setBackground(new java.awt.Color(217, 217, 217));
        txtharga.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtharga.setBorder(null);
        txtharga.setOpaque(false);
        getContentPane().add(txtharga, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 400, 270, 20));

        next.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nextMouseClicked(evt);
            }
        });
        getContentPane().add(next, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 600, 60, 60));

        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backMouseClicked(evt);
            }
        });
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 600, 60, 60));

        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMouseClicked(evt);
            }
        });
        getContentPane().add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 10, 50, 50));

        cari.setBackground(new java.awt.Color(217, 217, 217));
        cari.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cari.setBorder(null);
        cari.setOpaque(false);
        getContentPane().add(cari, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 540, 300, 20));

        txtstok.setBackground(new java.awt.Color(217, 217, 217));
        txtstok.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtstok.setBorder(null);
        txtstok.setOpaque(false);
        getContentPane().add(txtstok, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 340, 270, 20));

        txtbahan.setBackground(new java.awt.Color(217, 217, 217));
        txtbahan.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtbahan.setBorder(null);
        txtbahan.setOpaque(false);
        getContentPane().add(txtbahan, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 280, 270, 30));

        txtnama_barang.setBackground(new java.awt.Color(217, 217, 217));
        txtnama_barang.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtnama_barang.setBorder(null);
        txtnama_barang.setOpaque(false);
        getContentPane().add(txtnama_barang, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 220, 270, 30));

        txtkode_barang.setBackground(new java.awt.Color(217, 217, 217));
        txtkode_barang.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtkode_barang.setBorder(null);
        txtkode_barang.setOpaque(false);
        getContentPane().add(txtkode_barang, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 160, 270, 30));

        btncari.setBackground(new java.awt.Color(128, 165, 175));
        btncari.setText("Cari");
        btncari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncariActionPerformed(evt);
            }
        });
        getContentPane().add(btncari, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 530, 80, 40));

        batal.setBackground(new java.awt.Color(128, 165, 175));
        batal.setText("Batal");
        batal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                batalActionPerformed(evt);
            }
        });
        getContentPane().add(batal, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 470, 80, 40));

        hapus.setBackground(new java.awt.Color(128, 165, 175));
        hapus.setText("Hapus");
        hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusActionPerformed(evt);
            }
        });
        getContentPane().add(hapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 470, -1, 40));

        edit.setBackground(new java.awt.Color(128, 165, 175));
        edit.setText("Edit");
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });
        getContentPane().add(edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 470, 70, 40));

        simpan.setBackground(new java.awt.Color(128, 165, 175));
        simpan.setText("Simpan");
        simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanActionPerformed(evt);
            }
        });
        getContentPane().add(simpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 470, -1, 40));

        tabelbarang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabelbarang);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 90, 540, 480));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/databarang.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 700));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1230, 700));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusActionPerformed
        // TODO add your handling code here:
        try {
            java.sql.Connection conn = (java.sql.Connection) projectpbo.Konfig.configDB();
            String sql = "delete from barang where kode_barang='" + txtkode_barang.getText() + "' ";
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            pst.executeUpdate();

            JOptionPane.showMessageDialog(null, "Data berhasil di hapus");
            tampil_data();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Proses Penghapusan Gagal");
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_hapusActionPerformed

    private void exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseClicked
        // TODO add your handling code here:
         if (JOptionPane.showConfirmDialog(null, "Yakin Keluar aplikasi???",
            "Yakin", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
        this.dispose();
        }
    }//GEN-LAST:event_exitMouseClicked

    private void backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseClicked
        // TODO add your handling code here:
        try {
            String sql = "select * from pelanggan ";
            java.sql.Connection conn=(Connection)projectpbo.Konfig.configDB();
            java.sql.Statement stm=conn.createStatement();
            ResultSet rs = stm.executeQuery(sql);
        
            if(rs.next()){
                new menu().setVisible(true);
                dispose();
                this.pack();
                this.setLocationRelativeTo(null);
                this.setDefaultCloseOperation(login.EXIT_ON_CLOSE);
            }else{

            }
        } catch (Exception e) {
            System.out.println("Error "+e.getMessage());
        }
    }//GEN-LAST:event_backMouseClicked

    private void nextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nextMouseClicked
        // TODO add your handling code here:
        try{
            InputStream is =  pesanan.class.getResourceAsStream("/Laporan/barang.jasper");
            JasperPrint JsPrint = JasperFillManager.fillReport(is, null, Konfig.configDB());
            JasperViewer.viewReport(JsPrint, false);
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "gagal mencetak laporan karena :"
                    + e.getMessage(), "cetak laporan", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_nextMouseClicked

    private void btncariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncariActionPerformed
        // TODO add your handling code here:
        try {
            java.sql.Connection conn = (java.sql.Connection) project.Konfig.configDB();

            String sql = "Select * from barang where kode_barang='" + cari.getText() 
                    + "' or nama_barang='" + cari.getText()+"'";
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            ResultSet rs = pst.executeQuery(sql);
            if (rs.next()) {
                txtkode_barang.setText(rs.getString(1));
                txtnama_barang.setText(rs.getString(2));
                txtbahan.setText(rs.getString(3));
                txtstok.setText(rs.getString(4));
                txtharga.setText(rs.getString(5));
                
                tampil_data();
                JOptionPane.showMessageDialog(null, "Data order : "
                    + cari.getText() + " ditemukan, Apakah Anda Ingin Mengedit atau Menghapus?");
            }
                
            tampil();
            JOptionPane.showMessageDialog(null, "Data order : "+ cari.getText() + " ditemukan");
            
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btncariActionPerformed

    private void simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanActionPerformed
        // TODO add your handling code here:
        try {
            String sql = "insert into barang values('"
            + txtkode_barang.getText() + "','"
            + txtnama_barang.getText() + "','"
            + txtbahan.getText() + "','"
            + txtstok.getText() + "','"
            + txtharga.getText() + "'')";
            java.sql.Connection conn = (java.sql.Connection)
            projectpbo.Konfig.configDB();
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Berhasil disimpan");
            tampil();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Gagal disimpan");
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_simpanActionPerformed

    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed
        // TODO add your handling code here:
        try {
            java.sql.Connection conn = (java.sql.Connection) projectpbo.Konfig.configDB();
            String sql = "update barang set kode_barang='" + txtkode_barang.getText()
            + "', nama_barang = '" + txtnama_barang.getText()
            + "', bahan='" + txtbahan.getText() 
            + "', stok='" + txtstok.getText()
            + "', harga='" + txtharga.getText()
            + "' where kode_barang='" + txtkode_barang.getText() + "'";
            
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data berhasil di Koreksi");
            tampil_data();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Proses Edit data Gagal");
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_editActionPerformed

    private void batalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_batalActionPerformed
        // TODO add your handling code here:
        txtkode_barang.setText("");
        txtnama_barang.setText("");
        txtbahan.setText("");
        txtstok.setText("");
        txtharga.setText("");
        cari.setText("");
        txtkode_barang.requestFocus();
        tampil_data();
    }//GEN-LAST:event_batalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(databarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(databarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(databarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(databarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new databarang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel back;
    private javax.swing.JButton batal;
    private javax.swing.JButton btncari;
    private javax.swing.JTextField cari;
    private javax.swing.JButton edit;
    private javax.swing.JLabel exit;
    private javax.swing.JButton hapus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel next;
    private javax.swing.JButton simpan;
    private javax.swing.JTable tabelbarang;
    private javax.swing.JTextField txtbahan;
    private javax.swing.JTextField txtharga;
    private javax.swing.JTextField txtkode_barang;
    private javax.swing.JTextField txtnama_barang;
    private javax.swing.JTextField txtstok;
    // End of variables declaration//GEN-END:variables
}
